version: '1'
services:
  database:
    image: mysql:latest
    container_name: database
    ports:
      - 3336:3306
    restart: always
    environment:
      MYSQL_DATABASE: springapp
      #MYSQL_USER: root
      #MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
  spring-app:
    container_name: spring_app
    depends_on:
      - database
    ports:
      - 8080:8080
    image: 4f585207356e86cf919de8922e47e1a0d266e92841fcacdd6f5f0e0b8b481b40
    build: backend